# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\VS code\python\car_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.shibie = QtWidgets.QTabWidget(self.centralwidget)
        self.shibie.setGeometry(QtCore.QRect(30, 30, 761, 481))
        self.shibie.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.shibie.setObjectName("shibie")
        self.tab = QtWidgets.QWidget()
        self.tab.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tab.setToolTip("")
        self.tab.setStatusTip("")
        self.tab.setWhatsThis("")
        self.tab.setAccessibleName("")
        self.tab.setObjectName("tab")
        self.car_image = QtWidgets.QLabel(self.tab)
        self.car_image.setGeometry(QtCore.QRect(29, 39, 511, 361))
        self.car_image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.car_image.setFrameShape(QtWidgets.QFrame.Box)
        self.car_image.setLineWidth(3)
        self.car_image.setText("")
        self.car_image.setObjectName("car_image")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(570, 20, 151, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.car_lable_image = QtWidgets.QLabel(self.layoutWidget)
        self.car_lable_image.setFrameShape(QtWidgets.QFrame.Box)
        self.car_lable_image.setText("")
        self.car_lable_image.setObjectName("car_lable_image")
        self.verticalLayout_2.addWidget(self.car_lable_image)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.car_lable_01 = QtWidgets.QLabel(self.layoutWidget)
        self.car_lable_01.setFrameShape(QtWidgets.QFrame.Box)
        self.car_lable_01.setText("")
        self.car_lable_01.setObjectName("car_lable_01")
        self.verticalLayout_2.addWidget(self.car_lable_01)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.text_resulat = QtWidgets.QLabel(self.layoutWidget)
        self.text_resulat.setFrameShape(QtWidgets.QFrame.Box)
        self.text_resulat.setText("")
        self.text_resulat.setObjectName("text_resulat")
        self.verticalLayout_2.addWidget(self.text_resulat)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(600, 330, 95, 100))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_image = QtWidgets.QPushButton(self.layoutWidget1)
        self.open_image.setObjectName("open_image")
        self.verticalLayout.addWidget(self.open_image)
        self.shibei_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.shibei_button.setObjectName("shibei_button")
        self.verticalLayout.addWidget(self.shibei_button)
        self.quite_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.quite_button.setObjectName("quite_button")
        self.verticalLayout.addWidget(self.quite_button)
        self.shibie.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cap_show_label = QtWidgets.QLabel(self.tab_2)
        self.cap_show_label.setGeometry(QtCore.QRect(30, 20, 480, 360))
        self.cap_show_label.setFrameShape(QtWidgets.QFrame.Box)
        self.cap_show_label.setLineWidth(3)
        self.cap_show_label.setText("")
        self.cap_show_label.setObjectName("cap_show_label")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(110, 400, 330, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_cap_button = QtWidgets.QPushButton(self.widget)
        self.open_cap_button.setObjectName("open_cap_button")
        self.horizontalLayout.addWidget(self.open_cap_button)
        spacerItem = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.quite2_button = QtWidgets.QPushButton(self.widget)
        self.quite2_button.setObjectName("quite2_button")
        self.horizontalLayout.addWidget(self.quite2_button)
        self.shibie.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actiondakai = QtWidgets.QAction(MainWindow)
        self.actiondakai.setObjectName("actiondakai")

        self.retranslateUi(MainWindow)
        self.shibie.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "视觉测试"))
        self.label.setText(_translate("MainWindow", "车牌图片"))
        self.label_2.setText(_translate("MainWindow", "二值化"))
        self.label_3.setText(_translate("MainWindow", "识别结果"))
        self.open_image.setText(_translate("MainWindow", "打开文件"))
        self.shibei_button.setText(_translate("MainWindow", "识别"))
        self.quite_button.setText(_translate("MainWindow", "退出"))
        self.shibie.setTabText(self.shibie.indexOf(self.tab), _translate("MainWindow", "图片"))
        self.open_cap_button.setText(_translate("MainWindow", "打开摄像头"))
        self.quite2_button.setText(_translate("MainWindow", "退出"))
        self.shibie.setTabText(self.shibie.indexOf(self.tab_2), _translate("MainWindow", "视频"))
        self.actiondakai.setText(_translate("MainWindow", "打开"))
        self.actiondakai.setStatusTip(_translate("MainWindow", "点击打开文件"))

